import type { Metadata } from "next";
import { Inter , Gamja_Flower} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const gamja = Gamja_Flower({subsets:["latin"] , weight :["400"]});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div>
      {children}
      </div>
      </body>
    </html>
  );
}
